name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'

env:
  PORT: ${{ secrets.PORT }}
  HOST: ${{ secrets.HOST }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  REDIS_URL: ${{ secrets.REDIS_URL }}

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Jest
        run: |
          npm ci
          npm test-cover
